title: Artisanal Intelligence
description: A blog about artisanal intelligence
url: "https://artisanal-intelligence.info"
baseurl: ""  # keep empty unless serving under a subpath

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap

remote_theme: crankbird/crank-theme@main

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: true

timezone: Australia/Sydney

# Keep build clean
exclude:
  - node_modules
  - vendor
  - Gemfile*
  - README.md
  - _overrides.stash
  - _site